### ISSUE TITLE
Travis tests fail. The "Doctrine\Common\Inflector\Inflector::pluralize" method is deprecated

### ISSUE THREAD

**Issue by et-nik** [et-nik/gameap#47]
```
[2020-05-09 10:34:51] testing.ERROR: The "Doctrine\Common\Inflector\Inflector::pluralize" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API. {"userId":5,"exception":"[object] (RuntimeException(code: 0): The \"Doctrine\\Common\\Inflector\\Inflector::pluralize\" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API. at /home/travis/build/et-nik/gameap/vendor/knik/gameap-daemon-client/src/Gdaemon.php:174)
[stacktrace]
#0 [internal function]: Knik\\Gameap\\Gdaemon->Knik\\Gameap\\{closure}(16384, 'The \"Doctrine\\\\C...', '/home/travis/bu...', 261, Array)
#1 /home/travis/build/et-nik/gameap/vendor/doctrine/inflector/lib/Doctrine/Common/Inflector/Inflector.php(261): trigger_error('The \"Doctrine\\\\C...', 16384)
#2 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Support/Pluralizer.php(73): Doctrine\\Common\\Inflector\\Inflector::pluralize('Server')
#3 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Support/Str.php(364): Illuminate\\Support\\Pluralizer::plural('Server', 2)
#4 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Support/Str.php(380): Illuminate\\Support\\Str::plural('Server', 2)
#5 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1298): Illuminate\\Support\\Str::pluralStudly('DedicatedServer')
#6 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1255): Illuminate\\Database\\Eloquent\\Model->getTable()
#7 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(970): Illuminate\\Database\\Eloquent\\Builder->setModel(Object(Gameap\\Models\\DedicatedServer))
#8 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1005): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#9 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(958): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#10 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1622): Illuminate\\Database\\Eloquent\\Model->newQuery()
#11 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1483): Illuminate\\Database\\Eloquent\\Model->__call('where', Array)
#12 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php(37): Illuminate\\Database\\Eloquent\\Model->resolveRouteBinding('1')
#13 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(788): Illuminate\\Routing\\ImplicitRouteBinding::resolveForRoute(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Routing\\Route))
#14 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(39): Illuminate\\Routing\\Router->substituteImplicitBindings(Object(Illuminate\\Routing\\Route))
#15 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#31 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#32 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#33 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#34 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/travis/build/et-nik/gameap/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/travis/build/et-nik/gameap/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#50 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(468): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#51 /home/travis/build/et-nik/gameap/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(258): Illuminate\\Foundation\\Testing\\TestCase->call('GET', 'http://localhos...', Array, Array, Array, Array)
#52 /home/travis/build/et-nik/gameap/tests/Feature/Permissions/Controllers/Admin/DedicatedServersControllerTest.php(41): Illuminate\\Foundation\\Testing\\TestCase->get('http://localhos...')
#53 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/Framework/TestCase.php(1415): Tests\\Feature\\Permissions\\Controllers\\Admin\\DedicatedServersControllerTest->testAllow()
#54 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/Framework/TestCase.php(1035): PHPUnit\\Framework\\TestCase->runTest()
#55 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/Framework/TestResult.php(691): PHPUnit\\Framework\\TestCase->runBare()
#56 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/Framework/TestCase.php(763): PHPUnit\\Framework\\TestResult->run(Object(Tests\\Feature\\Permissions\\Controllers\\Admin\\DedicatedServersControllerTest))
#57 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/Framework/TestSuite.php(597): PHPUnit\\Framework\\TestCase->run(Object(PHPUnit\\Framework\\TestResult))
#58 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/Framework/TestSuite.php(597): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#59 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/Framework/TestSuite.php(597): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#60 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(621): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#61 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/TextUI/Command.php(204): PHPUnit\\TextUI\\TestRunner->doRun(Object(PHPUnit\\Framework\\TestSuite), Array, Array, true)
#62 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/src/TextUI/Command.php(163): PHPUnit\\TextUI\\Command->run(Array, true)
#63 /home/travis/build/et-nik/gameap/vendor/phpunit/phpunit/phpunit(61): PHPUnit\\TextUI\\Command::main()
#64 {main}
"} 
```

Waiting for Laravel PR https://github.com/laravel/framework/pull/32734

**Comment by et-nik** [comment]
Fixed in Laravel v6.18.14
